<?php
/**
 *
 * Wrtie [BCCFORM] in your post editor to render this shortcode.
 *
 * @package	 SWBCC
 * @since    1.0.0
 */

if (!function_exists('SW_BCC_shortcode'))
{
    add_action('plugins_loaded', function()
    {
        add_shortcode('BCCFORM', 'SW_BCC_shortcode');
    });

    /**
     * Bytion Coding Challenge Form ShortCode
     *
     * A shortcode which Authors can use to insert a HTML form into their content.
     * The form shouldinclude a name and email field, along with a submitbutton.
     *
     * @since    1.0.0
     * @return  A form to be displayed.
     **/

    function SW_BCC_shortcode()
    {
        SW_BCC_FORM();
        return '<div class="form">
      <form action="' . esc_url($_SERVER['REQUEST_URI']) . '" method="post">
      <div class="field">
        <label for="BCC_NAME">Name:</label>
        <input id="BCC_NAME" name="BCC_NAME" type="text">
      </div>
      <div class="field">
        <label for="BCC_EMAIL">Email Address:</label>
        <input id="BCC_EMAIL" name="BCC_EMAIL" type="email" >
      </div>
      <button name="BCC_FORM">Submit</button>
    </form>
  </div>';

    }
    /**
     * SWBCC Form Handler
     *
     * A handler of your choice to catch any form submission from the HTML
     * form generated by the shortcode. Form submissions should be saved to
     * the new database table and a success message displayed
     * to the user on the frontend.
     *
     * @since    2.0.0
     * @return a success message displayed to the user on the frontend.
     **/

    function SW_BCC_FORM()
    {
        if (isset($_POST['BCC_FORM']))
        {
            global $wpdb;
            $charset_collate = $wpdb->get_charset_collate();
            $table_name      = $wpdb->prefix . 'SWBCC';
            $name            = sanitize_text_field($_POST["BCC_NAME"]);
            $email           = sanitize_email($_POST["BCC_EMAIL"]);

            $table_name = $wpdb->prefix . 'SWBCC';

            $wpdb->insert($table_name, array(
                'name' => $name,
                'email' => $email
            ));

            echo 'Your Information was Succesfully Submitted!';
            unset($_POST['BCC_FORM']);


        }

    }
}
